- name: add apt repository
  apt_repository: repo='ppa:team-gcc-arm-embedded/ppa'
  become: yes

- name: apt-get install packages
  apt: name="{{ item.name }}" update_cache=yes
  with_items: "{{ apt_packages }}"
  become: yes
