- name: Get latest peco version
  shell: >
    curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^Location:/{print $NF}'
  register: peco_latest_version

- name: Download latest peco
  get_url: url=https://github.com/peco/peco/releases/download/{{ peco_latest_version.stdout }}/peco_linux_amd64.tar.gz dest=/home/vagrant/tmp/peco_linux_amd64.tar.gz

- name: Extract peco
  unarchive: src=/home/vagrant/tmp/peco_linux_amd64.tar.gz dest=/home/vagrant/tmp/ copy=no

- name: Copy to /usr/bin/
  command: cp /home/vagrant/tmp/peco_linux_amd64/peco /usr/bin/
  become: yes
